name: Sync app
on:
  push:

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: sylwit/install-b2-cli-action@v1.0.0
        env:
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPKEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPKEY }}

      - name: Sync
        run: b2 sync --compareVersions src b2://reactapp/src
        
        
        
        
        
        
        
       
